### ISSUE TITLE
Error Building on Windows

### ISSUE THREAD

**Issue by kealist** [metaeducation/ren-cpp#36]
Installed QT Creator package and added 5.4 to my search path.  Getting this error while building Ren Garden from the CMAKE file

```
C:\Users\kealist\Documents\GitHub\rencpp\examples\workbench>cmake cmakelists.txt
CMake Error at CMakeLists.txt:33 (remove_cxx_flag):
  Unknown CMake command "remove_cxx_flag".


-- Configuring incomplete, errors occurred!
See also "C:/Users/kealist/Documents/GitHub/rencpp/examples/workbench/CMakeFiles/CMakeOutput.log".
```

Using cmake version 2.8.12.2

**Comment by hostilefork** [comment]
As mentioned in chat, the current build process requires you to kick it all off from the root, and each subdir cmake file inherits things from the parent.  I don't know if it's possible to go from the reverse direction, it is sort of hierarchical.

The good news is, that when Ren Garden gets its own repository, you will be able to just go in the directory and build it.  The bad news is the dependency complexity will merely be different, because you'll have had to install RenCpp somewhere it can be found... sometimes you can't win.  :-)
